In [1]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (4.14.3)
Requirement already satisfied: pandas in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from requests) (2026.2.25)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\habii\appdata\local\programs\python\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import requests

In [3]:
from bs4 import BeautifulSoup

In [4]:
import pandas as pd

In [5]:
url = "http://books.toscrape.com"

In [6]:
response = requests.get(url)

In [7]:
print(response.status_code)

200

In [8]:
html_content = response.text

In [9]:
print(html_content[:1000])

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:29" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="static/oscar/favicon.

In [12]:
soup = BeautifulSoup(response.text , "html.parser")

In [13]:
print(type(soup))

<class 'bs4.BeautifulSoup'>

In [14]:
book = soup.find("h3")
print(book)

<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>

In [15]:
book_title = book.a["title"]
print(book_title)

A Light in the Attic

In [16]:
books = soup.find_all("h3")

for book in books:
    title = book.a["title"]
    print(title)

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

In [17]:
books = soup.find_all("h3")

book_titles = []

for book in books:
    title = book.a["title"]
    book_titles.append(title)

print(book_titles)

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind', 'The Requiem Red', 'The Dirty Little Secrets of Getting Your Dream Job', 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'The Black Maria', 'Starving Hearts (Triangular Trade Trilogy, #1)', "Shakespeare's Sonnets", 'Set Me Free', "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rip it Up and Start Again', 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Olio', 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Libertarianism for Beginners', "It's Only the Himalayas"]

In [18]:
import pandas as pd

df = pd.DataFrame(book_titles, columns=["Book Title"])

df.head()

                              Book Title
0                   A Light in the Attic
1                     Tipping the Velvet
2                             Soumission
3                          Sharp Objects
4  Sapiens: A Brief History of Humankind

In [19]:
df.to_csv("books_dataset.csv", index=False)

In [20]:
books = soup.find_all("article", class_="product_pod")

data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    rating = book.p["class"][1]
    availability = book.find("p", class_="instock availability").text.strip()

    data.append([title, price, rating, availability])

data

[['A Light in the Attic', 'Â£51.77', 'Three', 'In stock'],
 ['Tipping the Velvet', 'Â£53.74', 'One', 'In stock'],
 ['Soumission', 'Â£50.10', 'One', 'In stock'],
 ['Sharp Objects', 'Â£47.82', 'Four', 'In stock'],
 ['Sapiens: A Brief History of Humankind', 'Â£54.23', 'Five', 'In stock'],
 ['The Requiem Red', 'Â£22.65', 'One', 'In stock'],
 ['The Dirty Little Secrets of Getting Your Dream Job',
  'Â£33.34',
  'Four',
  'In stock'],
 ['The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
  'Â£17.93',
  'Three',
  'In stock'],
 ['The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'Â£22.60',
  'Four',
  'In stock'],
 ['The Black Maria', 'Â£52.15', 'One', 'In stock'],
 ['Starving Hearts (Triangular Trade Trilogy, #1)',
  'Â£13.99',
  'Two',
  'In stock'],
 ["Shakespeare's Sonnets", 'Â£20.66', 'Four', 'In stock'],
 ['Set Me Free', 'Â£17.46', 'Five', 'In stock'],
 ["Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
  'Â£52.29',
  'Five',
  'In stock'],
 ['Rip it Up and Start Again', 'Â£35.02', 'Five', 'In stock'],
 ['Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'Â£57.25',
  'Three',
  'In stock'],
 ['Olio', 'Â£23.88', 'One', 'In stock'],
 ['Mesaerion: The Best Science Fiction Stories 1800-1849',
  'Â£37.59',
  'One',
  'In stock'],
 ['Libertarianism for Beginners', 'Â£51.33', 'Two', 'In stock'],
 ["It's Only the Himalayas", 'Â£45.17', 'Two', 'In stock']]

In [21]:
import pandas as pd

df = pd.DataFrame(data, columns=["Title", "Price", "Rating", "Availability"])

df.head()

                                   Title    Price Rating Availability
0                   A Light in the Attic  Â£51.77  Three     In stock
1                     Tipping the Velvet  Â£53.74    One     In stock
2                             Soumission  Â£50.10    One     In stock
3                          Sharp Objects  Â£47.82   Four     In stock
4  Sapiens: A Brief History of Humankind  Â£54.23   Five     In stock

In [22]:
df.to_csv("books_full_dataset.csv", index=False)